[package]
name = "fatcrab-trading"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
crusty-n3xb = { path = "../crusty-n3xb" }
uuid = { version = "1.4", features = ["serde", "v4"] }
tokio = { version = "1.34", features = ["sync", "time"] }
secp256k1 = "0.27"
typetag = "0.2"
serde = { version = "1.0", features = ["derive", "rc"] }

[dev-dependencies]
anyhow = "1.0"
hyper = "0.14"
nostr-rs-relay = "0.8"
